export const CREATE_LISTING_REQUEST = "CREATE_LISTING_REQUEST";
export const CREATE_LISTING_SUCCESS = "CREATE_LISTING_SUCCESS";
export const CREATE_LISTING_FAIL = "CREATE_LISTING_FAIL";

export const GET_LISTINGS_REQUEST = "GET_LISTINGS_REQUEST";
export const GET_LISTINGS_SUCCESS = "GET_LISTINGS_SUCCESS";
export const GET_LISTINGS_FAIL = "GET_LISTINGS_FAIL";
